package com.packsendme.api.google.component;

import java.util.HashMap;
import java.util.Map;

import org.springframework.stereotype.Component;

@Component
public class RegionCountryRoadway_Component {
	
	private Map<String, String> locMap = new HashMap<String, String>();
	
	
	public RegionCountryRoadway_Component() {
		loadLocation();
	}

	private void loadLocation() {
		locMap.put("AF","Asia");
		locMap.put("AX","Europe");
		locMap.put("AL","Europe");
		locMap.put("DZ","Africa");
		locMap.put("AS","Oceania");
		locMap.put("AD","Europe");
		locMap.put("AO","Africa");
		locMap.put("AI","North America");
		locMap.put("AQ","Antarctica");
		locMap.put("AG","North America");
		locMap.put("AR","South America");
		locMap.put("AM","Asia");
		locMap.put("AW","North America");
		locMap.put("AU","Oceania");
		locMap.put("AT","Europe");
		locMap.put("AZ","Asia");
		locMap.put("BS","North America");
		locMap.put("BH","Asia");
		locMap.put("BD","Asia");
		locMap.put("BB","North America");
		locMap.put("BY","Europe");
		locMap.put("BE","Europe");
		locMap.put("BZ","North America");
		locMap.put("BJ","Africa");
		locMap.put("BM","North America");
		locMap.put("BT","Asia");
		locMap.put("BO","South America");
		locMap.put("BQ","North America");
		locMap.put("BA","Europe");
		locMap.put("BW","Africa");
		locMap.put("BV","Antarctica");
		locMap.put("BR","South America");
		locMap.put("IO","Asia");
		locMap.put("VG","North America");
		locMap.put("BN","Asia");
		locMap.put("BG","Europe");
		locMap.put("BF","Africa");
		locMap.put("BI","Africa");
		locMap.put("KH","Asia");
		locMap.put("CM","Africa");
		locMap.put("CA","North America");
		locMap.put("CV","Africa");
		locMap.put("KY","North America");
		locMap.put("CF","Africa");
		locMap.put("TD","Africa");
		locMap.put("CL","South America");
		locMap.put("CN","Asia");
		locMap.put("CX","Asia");
		locMap.put("CC","Asia");
		locMap.put("CO","South America");
		locMap.put("KM","Africa");
		locMap.put("CD","Africa");
		locMap.put("CG","Africa");
		locMap.put("CK","Oceania");
		locMap.put("CR","North America");
		locMap.put("CI","Africa");
		locMap.put("HR","Europe");
		locMap.put("CU","North America"); 
		locMap.put("CW","North America"); 
		locMap.put("CY","Asia"); 
		locMap.put("CZ","Europe"); 
		locMap.put("DK","Europe"); 
		locMap.put("DJ","Africa"); 
		locMap.put("DM","North America"); 
		locMap.put("DO","North America"); 
		locMap.put("EC","South America"); 
		locMap.put("EG","Africa"); 
		locMap.put("SV","North America"); 
		locMap.put("GQ","Africa"); 
		locMap.put("ER","Africa"); 
		locMap.put("EE","Europe"); 
		locMap.put("ET","Africa"); 
		locMap.put("FO","Europe"); 
		locMap.put("FK","South America"); 
		locMap.put("FJ","Oceania"); 
		locMap.put("FI","Europe"); 
		locMap.put("FR","Europe"); 
		locMap.put("GF","South America"); 
		locMap.put("PF","Oceania"); 
		locMap.put("TF","Antarctica"); 
		locMap.put("GA","Africa"); 
		locMap.put("GM","Africa"); 
		locMap.put("GE","Asia"); 
		locMap.put("DE","Europe"); 
		locMap.put("GH","Africa"); 
		locMap.put("GI","Europe"); 
		locMap.put("GR","Europe"); 
		locMap.put("GL","North America"); 
		locMap.put("GD","North America"); 
		locMap.put("GP","North America"); 
		locMap.put("GU","Oceania"); 
		locMap.put("GT","North America"); 
		locMap.put("GG","Europe"); 
		locMap.put("GN","Africa"); 
		locMap.put("GW","Africa"); 
		locMap.put("GY","South America"); 
		locMap.put("HT","North America"); 
		locMap.put("HM","Antarctica"); 
		locMap.put("VA","Europe"); 
		locMap.put("HN","North America"); 
		locMap.put("HK","Asia"); 
		locMap.put("HU","Europe"); 
		locMap.put("IS","Europe"); 
		locMap.put("IN","Asia");
		locMap.put("ID","Asia"); 
		locMap.put("IR","Asia"); 
		locMap.put("IQ","Asia"); 
		locMap.put("IE","Europe"); 
		locMap.put("IM","Europe"); 
		locMap.put("IL","Asia"); 
		locMap.put("IT","Europe"); 
		locMap.put("JM","North America"); 
		locMap.put("JP","Asia"); 
		locMap.put("JE","Europe"); 
		locMap.put("JO","Asia"); 
		locMap.put("KZ","Asia"); 
		locMap.put("KE","Africa"); 
		locMap.put("KI","Oceania"); 
		locMap.put("KP","Asia"); 
		locMap.put("KR","Asia"); 
		locMap.put("KW","Asia"); 
		locMap.put("KG","Asia"); 
		locMap.put("LA","Asia"); 
		locMap.put("LV","Europe"); 
		locMap.put("LB","Asia"); 
		locMap.put("LS","Africa"); 
		locMap.put("LR","Africa"); 
		locMap.put("LY","Africa"); 
		locMap.put("LI","Europe"); 
		locMap.put("LT","Europe"); 
		locMap.put("LU","Europe"); 
		locMap.put("MO","Asia"); 
		locMap.put("MK","Europe"); 
		locMap.put("MG","Africa"); 
		locMap.put("MW","Africa"); 
		locMap.put("MY","Asia"); 
		locMap.put("MV","Asia"); 
		locMap.put("ML","Africa"); 
		locMap.put("MT","Europe"); 
		locMap.put("MH","Oceania"); 
		locMap.put("MQ","North America"); 
		locMap.put("MR","Africa"); 
		locMap.put("MU","Africa"); 
		locMap.put("YT","Africa"); 
		locMap.put("MX","North America"); 
		locMap.put("FM","Oceania"); 
		locMap.put("MD","Europe"); 
		locMap.put("MC","Europe"); 
		locMap.put("MN","Asia"); 
		locMap.put("ME","Europe"); 
		locMap.put("MS","North America"); 
		locMap.put("MA","Africa"); 
		locMap.put("MZ","Africa"); 
		locMap.put("MM","Asia"); 
		locMap.put("NA","Africa"); 
		locMap.put("NR","Oceania"); 
		locMap.put("NP","Asia"); 
		locMap.put("NL","Europe"); 
		locMap.put("NC","Oceania"); 
		locMap.put("NZ","Oceania"); 
		locMap.put("NI","North America"); 
		locMap.put("NE","Africa"); 
		locMap.put("NG","Africa"); 
		locMap.put("NU","Oceania"); 
		locMap.put("NF","Oceania"); 
		locMap.put("MP","Oceania"); 
		locMap.put("NO","Europe"); 
		locMap.put("OM","Asia"); 
		locMap.put("PK","Asia"); 
		locMap.put("PW","Oceania");
		locMap.put("PS","Asia"); 
		locMap.put("PA","North America"); 
		locMap.put("PG","Oceania"); 
		locMap.put("PY","South America"); 
		locMap.put("PE","South America"); 
		locMap.put("PH","Asia"); 
		locMap.put("PN","Oceania"); 
		locMap.put("PL","Europe"); 
		locMap.put("PT","Europe"); 
		locMap.put("PR","North America"); 
		locMap.put("QA","Asia"); 
		locMap.put("RE","Africa"); 
		locMap.put("RO","Europe"); 
		locMap.put("RU","Europe"); 
		locMap.put("RW","Africa"); 
		locMap.put("BL","North America"); 
		locMap.put("SH","Africa"); 
		locMap.put("KN","North America"); 
		locMap.put("LC","North America"); 
		locMap.put("MF","North America"); 
		locMap.put("PM","North America"); 
		locMap.put("VC","North America"); 
		locMap.put("WS","Oceania"); 
		locMap.put("SM","Europe");
		locMap.put("ST","Africa"); 
		locMap.put("SA","Asia"); 
		locMap.put("SN","Africa"); 
		locMap.put("RS","Europe"); 
		locMap.put("SC","Africa"); 
		locMap.put("SL","Africa"); 
		locMap.put("SG","Asia"); 
		locMap.put("SX","North America"); 
		locMap.put("SK","Europe"); 
		locMap.put("SI","Europe"); 
		locMap.put("SB","Oceania"); 
		locMap.put("SO","Africa"); 
		locMap.put("ZA","Africa"); 
		locMap.put("GS","Antarctica"); 
		locMap.put("SS","Africa"); 
		locMap.put("ES","Europe"); 
		locMap.put("LK","Asia"); 
		locMap.put("SD","Africa"); 
		locMap.put("SR","South America"); 
		locMap.put("SJ","Europe"); 
		locMap.put("SZ","Africa"); 
		locMap.put("SE","Europe"); 
		locMap.put("CH","Europe"); 
		locMap.put("SY","Asia"); 
		locMap.put("TW","Asia");
		locMap.put("TJ","Asia"); 
		locMap.put("TZ","Africa"); 
		locMap.put("TH","Asia"); 
		locMap.put("TL","Asia"); 
		locMap.put("TG","Africa"); 
		locMap.put("TK","Oceania"); 
		locMap.put("TO","Oceania"); 
		locMap.put("TT","North America"); 
		locMap.put("TN","Africa"); 
		locMap.put("TR","Asia"); 
		locMap.put("TM","Asia"); 
		locMap.put("TC","North America"); 
		locMap.put("TV","Oceania"); 
		locMap.put("UG","Africa"); 
		locMap.put("UA","Europe"); 
		locMap.put("AE","Asia"); 
		locMap.put("GB","Europe"); 
		locMap.put("US","North America"); 
		locMap.put("UM","Oceania"); 
		locMap.put("VI","North America"); 
		locMap.put("UY","South America"); 
		locMap.put("UZ","Asia"); 
		locMap.put("VU","Oceania"); 
		locMap.put("VE","South America"); 
		locMap.put("VN","Asia"); 
		locMap.put("WF","Oceania"); 
		locMap.put("EH","Africa"); 
		locMap.put("YE","Asia"); 
		locMap.put("ZM","Africa"); 
		locMap.put("ZW","Africa"); 
	}
	
	public String findCountry(String key) {
		System.out.println(" ");
		System.out.println(" ------------------------------ ");
		System.out.println(" VALOR KEY "+ key);
		System.out.println(" ------------------------------ ");
		return locMap.get(key).toString();
	}

	

}
